server:
   port: 8888 #convenção usar a porta 8888 para config server
  
spring:
  application:
    name: spring-cloud-config-server
#  profiles: # apontar para o arquivo local
#    active:
#      - native
  # apontar para o GITHUB
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thi-rodrigues/config-server-global
          search-paths: 'greeting-service*'
#          username: username
#          password: password
          default-label: main #apontar para qual a branch
#